version: '3.8'

services:
  # Next.js 프론트엔드 (SSR)
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tbc-frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE=http://localhost/api
    depends_on:
      - api
    networks:
      - tbc-network
    restart: unless-stopped

  # 백엔드 API
  api:
    build:
      context: ../tbc-back  # 백엔드 프로젝트 경로로 수정
      dockerfile: Dockerfile
    container_name: tbc-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8080
    networks:
      - tbc-network
    restart: unless-stopped

  # Nginx 프록시
  nginx:
    image: nginx:alpine
    container_name: tbc-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl  # SSL 인증서 (선택사항)
    depends_on:
      - nextjs
      - api
    networks:
      - tbc-network
    restart: unless-stopped

networks:
  tbc-network:
    driver: bridge
