spring:
  datasource:
    url: jdbc:mysql://192.168.219.70:3306/tbc_db?
    serverTimezone: Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: tbc
    password: EjrqhR21!

