server:
  port: 8080
  error:
    include-message: ALWAYS
    include-binding-errors: ALWAYS
    include-stacktrace: ALWAYS
  servlet:
    session:
      cookie:
        secure: false
        same-site: none
        http-only: true

spring:
  datasource:
    url: jdbc:mysql://192.168.219.70:3306/tbc_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: tbc
    password: EjrqhR21!
  jpa:
    hibernate:
      ddl-auto: update   # 개발 시 자동 갱신
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  sql:
    init:
      mode: never

logging:
  level:
    org.springframework.web.socket: DEBUG
    org.springframework.web.socket.server: DEBUG

jwt:
  secret: CHANGE_ME_TO_A_LONG_RANDOM_SECRET_64+_CHARS
  access-expiration-minutes: 15
  refresh-expiration-days: 14

app:
  cookie:
    secure: true
    same-site: None
    access-name: access
    refresh-name: refresh

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

chat:
  max-content-length: 1000
  max-qps-per-session: 10
