server:
  port: 8081
  error:
    include-message: NEVER   # 배포 환경에서는 상세 에러 노출 금지
    include-binding-errors: NEVER
    include-stacktrace: NEVER
  servlet:
    session:
      cookie:
        secure: true
        same-site: none
        http-only: true

spring:
  datasource:
    url: jdbc:mysql://<PROD-RDS-ENDPOINT>:3306/tbc_db?useSSL=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none        # 배포 환경은 스키마 자동 갱신 금지
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
  sql:
    init:
      mode: never

logging:
  level:
    root: INFO

jwt:
  secret: ${JWT_SECRET}
  access-expiration-minutes: 15
  refresh-expiration-days: 14

app:
  cookie:
    secure: true
    same-site: None
    access-name: access
    refresh-name: refresh

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
